### PR TITLE
Bug fixes for dotenv support

### PR DESCRIPTION
**Pull request by sank8dalvi**
#10

### CODE REVIEW

**Comment by 0xjas0** [comment]
Please do test your code before making a PR request as I'm not verifying it again for this particular repo
I'm adding it to pending till then

And also are you making this PR for hacktoberfest ?
So that if you are I'll add it in hacktoberfest label

**Comment by sank8dalvi** [comment]
I understand that you haven't added automated testing for this repository and that's why I have performed several tests before creating this PR.
It's okay if you don't add the hacktoberfest label. I am contributing for the benefit of the community.

**Comment by 0xjas0** [comment]
Ok Approving it

**Comment by sank8dalvi** [comment]
Thank you

**Pull request merged**
